version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'production_sensors'
      MYSQL_USER: 'sensor-user'
      MYSQL_PASSWORD: 'sensor-password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      production-sensors-network:
        aliases:
          - production-sensors-network

  app:
    container_name: production-sensors-api
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        GID: '1000'
        UID: '1000'
        UNAME: 'nejcm'
    user: 'root'
    restart: 'always'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    ports:
      - '8888:8888'
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.prod
    networks:
      production-sensors-network:
        aliases:
          - production-sensors-network
    volumes:
      - ./storage:/var/www/storage
      - ./.env.stage:/var/www/.env.stage
    working_dir: /var/www/
    depends_on:
      - mysql

networks:
  production-sensors-network:
    driver: bridge
volumes:
  db_data:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
