# For more information: https://laravel.com/docs/sail
services:
  mysql:
    image: mysql:8.0
    container_name: sensors-mysql
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'production_sensors'
      MYSQL_USER: 'sensor-user'
      MYSQL_PASSWORD: 'sensor-password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      sensors-network:
        aliases:
          - sensors-network

  app:
    container_name: dev-sensors-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GID: '1000'
        UID: '1000'
        UNAME: 'nejcm'
    user: 'root'
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8888"
    tty: true
    ports:
      - '8888:8888'
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      sensors-network:
        aliases:
          - sensors-network
    volumes:
      - ./:/var/www/
      - ./.env.dev:/var/www/.env
    working_dir: /var/www/
    depends_on:
      - mysql

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: sensors-smtp-server
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      sensors-network:
        aliases:
          - sensors-network

networks:
  sensors-network:
    name: sensors-network
    driver: bridge
volumes:
  db_data:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
